{
    "capabilities": {
        "browserName": "firefox",
        "moz:firefoxOptions": {
            "args": [
                "-disable-gpu",
                "-disable-dev-shm-usage",
                "-headless"
                    ],
            "prefs": {
                "geo.enabled": true,
                "geo.provider.use_corelocation": true,
                "geo.prompt.testing": true,
                "geo.prompt.testing.allow": true
            }
        }
    }
}